#ifndef FAULTS_H
#define FAULTS_H
#include <stdint.h>
enum { FAULT_NONE=0U, FAULT_VISION_TIMEOUT=1U<<0, FAULT_VISION_INVALID=1U<<1, FAULT_SOFT_LIMIT=1U<<2, FAULT_TASK_TIMEOUT=1U<<3, FAULT_PROTOCOL=1U<<4, FAULT_MOTOR_SEMANTICS=1U<<5 };
#endif
